services:
  - type: web
    name: maxit-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      mkdir -p public/uploads
      chmod 755 public/uploads
    startCommand: |
      cd public && php -S 0.0.0.0:$PORT index.php
    envVars:
      - key: DB_HOST
        value: yamanote.proxy.rlwy.net
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: eZkXltxHmZcJPrredZqdnxPXxfmWnfgH
      - key: MYSQL_PORT
        value: 30123
      - key: DB_DRIVER
        value: mysql
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: UPLOAD_DIR
        value: public/uploads
      - key: UPLOAD_MAX_SIZE
        value: 5242880
      - key: AUTH_URL
        value: https://appwoyofal-qljz.onrender.com
